// Wails v2 runtime type declarations
// These are auto-generated by Wails during development; this stub enables TypeScript compilation.

export function EventsOn(eventName: string, callback: (...data: any) => void): () => void;
export function EventsOff(eventName: string, ...additionalEventNames: string[]): void;
export function EventsOnce(eventName: string, callback: (...data: any) => void): () => void;
export function EventsOnMultiple(eventName: string, callback: (...data: any) => void, maxCallbacks: number): () => void;
export function EventsEmit(eventName: string, ...data: any): void;

export function WindowReload(): void;
export function WindowSetTitle(title: string): void;
export function WindowFullscreen(): void;
export function WindowUnfullscreen(): void;
export function WindowMinimise(): void;
export function WindowUnminimise(): void;
export function WindowMaximise(): void;
export function WindowUnmaximise(): void;
export function WindowCenter(): void;

export function LogPrint(message: string): void;
export function LogTrace(message: string): void;
export function LogDebug(message: string): void;
export function LogInfo(message: string): void;
export function LogWarning(message: string): void;
export function LogError(message: string): void;
export function LogFatal(message: string): void;

export function Quit(): void;
export function Environment(): Promise<any>;
